//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int Id { get; set; }
        public double Amount { get; set; }
        public System.DateTime date { get; set; }
        public string time { get; set; }
        public string UserId { get; set; }
        public int seatno { get; set; }
        public int MovieId { get; set; }
    }
}
